export enum loginLocators {
    GET_STARTED_BUTTON = "//*[@resource-id='com.hdw.james.rider:id/getStartedButton']",
    PHONE_PREFIX = "//*[@resource-id='com.hdw.james.rider:id/spinner']",
    PREFIX_LIST = '/hierarchy/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.ListView',
    AFGHANISTAN_PHONE = '//*[@text=" Afghanistan (+93)"]',
    ALBANIA_PHONE = '//*[@text=" Albania (+355)"]',
    PHONE_INPUT = "//*[@resource-id='com.hdw.james.rider:id/input']",
    INPUT_BUTTON = "//*[@resource-id='com.hdw.james.rider:id/continueButton']",
    VERSION = "//*[@resource-id='com.hdw.james.rider:id/version']",
    INPUT_GENERIC = "//*/android.widget.LinearLayout[{n}]/android.widget.FrameLayout/android.widget.EditText",
    VERIFICATION_BUTTON = "//*[@resource-id='com.hdw.james.rider:id/continueButton']",
    ENTER_6_DIGIT = "//*[@resource-id='com.hdw.james.rider:id/title']",
    PERMISSION_REQUEST_TEXT = "//*[@text='Permissions Request']",
    DESCRIPTION_PERMISSION_TEXT = "//*[@resource-id='com.hdw.james.rider:id/permissionsText']",
    HOW_DOES_IT_WORK_TEXT = "//*[@text='How does it work?']",
    PERMISSION_CONTINUE = "//*[@resource-id='com.hdw.james.rider:id/permissionsContinueButton']",
    ENTER_PHONE_NUMBER = "//*[@text='Enter your phone number']",
}